/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MajicalMathMethods;

/**
 *
 * @author pehor9164
 */
public class MajicalMathMethods extends javax.swing.JFrame {

    /**
     * Creates new form MajicalMathMethods
     */
    public MajicalMathMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGroundJPanel = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        largerPromptLbl = new javax.swing.JLabel();
        largerTxtFeild2 = new javax.swing.JTextField();
        smallerTxtFeild2 = new javax.swing.JTextField();
        radialsBtn = new javax.swing.JButton();
        smallerPromptLbl = new javax.swing.JLabel();
        largerTxtFeild1 = new javax.swing.JTextField();
        powerTxtFeild2 = new javax.swing.JTextField();
        largestBtn = new javax.swing.JButton();
        powerPromptLbl = new javax.swing.JLabel();
        smallerTxtFeild1 = new javax.swing.JTextField();
        hypotenuseTxtFeild2 = new javax.swing.JTextField();
        smallerBtn = new javax.swing.JButton();
        hypotenusePromptLbl = new javax.swing.JLabel();
        powerTxtFeild1 = new javax.swing.JTextField();
        radialsTxtFeild1 = new javax.swing.JTextField();
        powerBtn = new javax.swing.JButton();
        roundDownPromptLbl = new javax.swing.JLabel();
        hypotenuseTxtFeild1 = new javax.swing.JTextField();
        hypotenuseBtn = new javax.swing.JButton();
        roundUpPromptLbl = new javax.swing.JLabel();
        roundDownTxtFeild1 = new javax.swing.JTextField();
        roundDownBtn = new javax.swing.JButton();
        squareRootPromptLbl = new javax.swing.JLabel();
        roundUpTxtFeild1 = new javax.swing.JTextField();
        roundUpBtn = new javax.swing.JButton();
        radialsPromptLbl = new javax.swing.JLabel();
        squareRootTxtFeild1 = new javax.swing.JTextField();
        squareRootBtn = new javax.swing.JButton();
        radialsOutputLbl = new javax.swing.JLabel();
        largestOutputLbl = new javax.swing.JLabel();
        smallestOutputLbl = new javax.swing.JLabel();
        powerOutputLbl = new javax.swing.JLabel();
        hypoenuseOutputLbl = new javax.swing.JLabel();
        roundedDownOutputLbl = new javax.swing.JLabel();
        roundedUpOutputLbl = new javax.swing.JLabel();
        squareRootOutputLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backGroundJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 204, 0));
        titleLbl.setText("Magical Math Methods");
        backGroundJPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        largerPromptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        largerPromptLbl.setText("Enter two numbers and press the button. The program will output the larger number");
        backGroundJPanel.add(largerPromptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 540, -1));

        largerTxtFeild2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largerTxtFeild2ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(largerTxtFeild2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 30, 30));

        smallerTxtFeild2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallerTxtFeild2ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(smallerTxtFeild2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 30, 30));

        radialsBtn.setText("Number In Radials");
        radialsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radialsBtnActionPerformed(evt);
            }
        });
        backGroundJPanel.add(radialsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 120, 30));

        smallerPromptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        smallerPromptLbl.setText("Enter two numbers and press the button. The program will output the smaller number");
        backGroundJPanel.add(smallerPromptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        largerTxtFeild1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largerTxtFeild1ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(largerTxtFeild1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 30, 30));

        powerTxtFeild2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerTxtFeild2ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(powerTxtFeild2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 30, 30));

        largestBtn.setText("Lergest");
        largestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largestBtnActionPerformed(evt);
            }
        });
        backGroundJPanel.add(largestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 120, 30));

        powerPromptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        powerPromptLbl.setText("Enter two numbers and press the button. the program will output the total of the first number to the power of the second");
        backGroundJPanel.add(powerPromptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        smallerTxtFeild1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallerTxtFeild1ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(smallerTxtFeild1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 30));

        hypotenuseTxtFeild2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypotenuseTxtFeild2ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(hypotenuseTxtFeild2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 30, 30));

        smallerBtn.setText("Smallest");
        smallerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallerBtnActionPerformed(evt);
            }
        });
        backGroundJPanel.add(smallerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, 30));

        hypotenusePromptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hypotenusePromptLbl.setText("Enter two lengths of a right angle triangle. The program will output the hypotenuse of the triangle.");
        backGroundJPanel.add(hypotenusePromptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        powerTxtFeild1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerTxtFeild1ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(powerTxtFeild1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 30, 30));

        radialsTxtFeild1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radialsTxtFeild1ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(radialsTxtFeild1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 30, 30));

        powerBtn.setText("Power");
        powerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerBtnActionPerformed(evt);
            }
        });
        backGroundJPanel.add(powerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 120, 30));

        roundDownPromptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roundDownPromptLbl.setText("Enter a decimal number. The program will output the number rounded down to the nearest integer. ");
        backGroundJPanel.add(roundDownPromptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        hypotenuseTxtFeild1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypotenuseTxtFeild1ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(hypotenuseTxtFeild1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 30, 30));

        hypotenuseBtn.setText("Hypotenuse");
        hypotenuseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypotenuseBtnActionPerformed(evt);
            }
        });
        backGroundJPanel.add(hypotenuseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 120, 30));

        roundUpPromptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roundUpPromptLbl.setText("Enter a decimal number. The program will output the number rounded up to the nearest integer. ");
        backGroundJPanel.add(roundUpPromptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        roundDownTxtFeild1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundDownTxtFeild1ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(roundDownTxtFeild1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 30, 30));

        roundDownBtn.setText("Rounded Down");
        roundDownBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundDownBtnActionPerformed(evt);
            }
        });
        backGroundJPanel.add(roundDownBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 120, 30));

        squareRootPromptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        squareRootPromptLbl.setText("Enter a number and press the button. The program will output the numbers square root.");
        backGroundJPanel.add(squareRootPromptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        roundUpTxtFeild1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundUpTxtFeild1ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(roundUpTxtFeild1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 30, 30));

        roundUpBtn.setText("Rounded Up");
        roundUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundUpBtnActionPerformed(evt);
            }
        });
        backGroundJPanel.add(roundUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 120, 30));

        radialsPromptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radialsPromptLbl.setText("Enter an angle in degrees. The program will output the number in radials.");
        backGroundJPanel.add(radialsPromptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        squareRootTxtFeild1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareRootTxtFeild1ActionPerformed(evt);
            }
        });
        backGroundJPanel.add(squareRootTxtFeild1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 30, 30));

        squareRootBtn.setText("Square Root");
        squareRootBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareRootBtnActionPerformed(evt);
            }
        });
        backGroundJPanel.add(squareRootBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 120, 30));

        radialsOutputLbl.setText("...");
        backGroundJPanel.add(radialsOutputLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 640, -1, -1));

        largestOutputLbl.setText("...");
        backGroundJPanel.add(largestOutputLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        smallestOutputLbl.setText("...");
        backGroundJPanel.add(smallestOutputLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        powerOutputLbl.setText("...");
        backGroundJPanel.add(powerOutputLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        hypoenuseOutputLbl.setText("...");
        backGroundJPanel.add(hypoenuseOutputLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        roundedDownOutputLbl.setText("...");
        backGroundJPanel.add(roundedDownOutputLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        roundedUpOutputLbl.setText("...");
        backGroundJPanel.add(roundedUpOutputLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, -1));

        squareRootOutputLbl.setText("...");
        backGroundJPanel.add(squareRootOutputLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGroundJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backGroundJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void largerTxtFeild2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largerTxtFeild2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largerTxtFeild2ActionPerformed

    private void smallerTxtFeild2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallerTxtFeild2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallerTxtFeild2ActionPerformed

    private void radialsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radialsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radialsBtnActionPerformed

    private void largerTxtFeild1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largerTxtFeild1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largerTxtFeild1ActionPerformed

    private void powerTxtFeild2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerTxtFeild2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powerTxtFeild2ActionPerformed

    private void largestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largestBtnActionPerformed

    private void smallerTxtFeild1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallerTxtFeild1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallerTxtFeild1ActionPerformed

    private void hypotenuseTxtFeild2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypotenuseTxtFeild2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hypotenuseTxtFeild2ActionPerformed

    private void smallerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallerBtnActionPerformed

    private void powerTxtFeild1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerTxtFeild1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powerTxtFeild1ActionPerformed

    private void radialsTxtFeild1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radialsTxtFeild1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radialsTxtFeild1ActionPerformed

    private void powerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powerBtnActionPerformed

    private void hypotenuseTxtFeild1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypotenuseTxtFeild1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hypotenuseTxtFeild1ActionPerformed

    private void hypotenuseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypotenuseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hypotenuseBtnActionPerformed

    private void roundDownTxtFeild1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundDownTxtFeild1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundDownTxtFeild1ActionPerformed

    private void roundDownBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundDownBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundDownBtnActionPerformed

    private void roundUpTxtFeild1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundUpTxtFeild1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundUpTxtFeild1ActionPerformed

    private void roundUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundUpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundUpBtnActionPerformed

    private void squareRootTxtFeild1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareRootTxtFeild1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_squareRootTxtFeild1ActionPerformed

    private void squareRootBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareRootBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_squareRootBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MajicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MajicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MajicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MajicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MajicalMathMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backGroundJPanel;
    private javax.swing.JLabel hypoenuseOutputLbl;
    private javax.swing.JButton hypotenuseBtn;
    private javax.swing.JLabel hypotenusePromptLbl;
    private javax.swing.JTextField hypotenuseTxtFeild1;
    private javax.swing.JTextField hypotenuseTxtFeild2;
    private javax.swing.JLabel largerPromptLbl;
    private javax.swing.JTextField largerTxtFeild1;
    private javax.swing.JTextField largerTxtFeild2;
    private javax.swing.JButton largestBtn;
    private javax.swing.JLabel largestOutputLbl;
    private javax.swing.JButton powerBtn;
    private javax.swing.JLabel powerOutputLbl;
    private javax.swing.JLabel powerPromptLbl;
    private javax.swing.JTextField powerTxtFeild1;
    private javax.swing.JTextField powerTxtFeild2;
    private javax.swing.JButton radialsBtn;
    private javax.swing.JLabel radialsOutputLbl;
    private javax.swing.JLabel radialsPromptLbl;
    private javax.swing.JTextField radialsTxtFeild1;
    private javax.swing.JButton roundDownBtn;
    private javax.swing.JLabel roundDownPromptLbl;
    private javax.swing.JTextField roundDownTxtFeild1;
    private javax.swing.JButton roundUpBtn;
    private javax.swing.JLabel roundUpPromptLbl;
    private javax.swing.JTextField roundUpTxtFeild1;
    private javax.swing.JLabel roundedDownOutputLbl;
    private javax.swing.JLabel roundedUpOutputLbl;
    private javax.swing.JButton smallerBtn;
    private javax.swing.JLabel smallerPromptLbl;
    private javax.swing.JTextField smallerTxtFeild1;
    private javax.swing.JTextField smallerTxtFeild2;
    private javax.swing.JLabel smallestOutputLbl;
    private javax.swing.JButton squareRootBtn;
    private javax.swing.JLabel squareRootOutputLbl;
    private javax.swing.JLabel squareRootPromptLbl;
    private javax.swing.JTextField squareRootTxtFeild1;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
